paths:
  /api/products:
    get:
      summary: Devuelve los productos de la base de datos
      tags:
        - Products
      responses:
        "200":
          description: Los Productos se encontraron satisfactoriamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status de la operaci贸n
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "500":
          description: Error del servidor. Revisar que la conexi贸n a la base de datos sea consistente.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: integer
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripci贸n del producto
        code:
          type: string
          description: C贸digo del producto
        stock:
          type: integer
          description: Cantidad de Productos
        price:
          type: integer
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen
